# Style Guide AI - Docker Compose Configuration
# 
# 🚀 OPTIMIZATION: This setup uses Docker layer caching!
# - Python dependencies - cached (unless requirements.txt changes)
# - NLP models - cached
# - Ruby gems - cached
#
# Only rebuilds when you change:
# - App code (fast rebuild)
# - requirements.txt (rebuilds dependencies)
# - System dependencies

version: '3.8'

services:
  style-guide-ai:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: quay.io/rhdeveldocs/style-guide-ai:latest
    container_name: style-guide-ai
    ports:
      - "5000:5000"    # Flask app (change to "8080:5000" if port 5000 is in use)
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s 