# config/exceptions.yaml
# ----------------------
# UPDATED based on Test Suite 1 results.
# This file provides a centralized allowlist to prevent the style analyzer
# from flagging correct, context-specific terms as errors.

# Global exceptions apply to all rules.
global_exceptions:
  - "end-of-life"
  - "out-of-the-box"
  - "General Availability"
  - "DevOps"
  - "GitOps"
  - "MySQL"
  - "PostgreSQL"
  - "{ocp-brand-name}"
  - "{product}"

# Rule-specific exceptions provide more granular control over individual rules.
rule_specific_exceptions:
  
  # Exceptions for the 'second_person' rule.
  # ADDED "end user" to prevent the false positive found in Block 6.
  second_person:
    - "user interface"
    - "user experience"
    - "user credentials"
    - "user account"
    - "user group"
    - "user profile"
    - "user session"
    - "end user" # <-- ADDED
    - "service mesh"
    - "serverless functions"
    - "distributed tracing"

  # Exceptions for a potential 'anthropomorphism' rule.
  # ADDED "allows" and "provides" to prevent false positives.
  anthropomorphism:
    - "provide"
    - "allow"     # <-- ADDED
    - "enable"
    - "ensure"
    - "support"
    - "check"
    - "read"
    - "write"
    - "detect"
    - "display"
    - "offer"
    - "manage"
    - "send"
    - "receive"

  # Exceptions for the 'headings' rule.
  headings:
    - "Overview"
    - "Features"
    - "Benefits"
    - "Requirements"
    - "Limitations"
    - "Considerations"
    - "Logging"
    - "logging"

  # Exceptions for the 'claims' rule to reduce noise from the ambiguity checker.
  claims:
    - "easy management"
    - "secure"
    - "full integration"
    - "high availability"
    - "large-scale"
    - "end-to-end encryption"
    - "real-time feedback"

  # Exceptions for the 'capitalization' rule to prevent flagging common words.
  capitalization:
    - "you"
    - "ensure"
    - "save" 
    - "and"
    - "but"
    - "the"
    - "friendly"
    - "etc"
    - "address"
    - "requisites"
    - "make"
    - "sure"
    - "can"
    - "will"
    - "should"
    - "would"
    - "could"
    - "might"
    - "may"
    - "must"
    - "need"
    - "want"
    - "have"
    - "has"
    - "had"
    - "get"
    - "got"
    - "put"
    - "set"
    - "run"
    - "use"
    - "see"
    - "go"
    - "do"
    - "be"
    - "is"
    - "are"
    - "was"
    - "were"
    - "been"
    - "being"
    - "at"
    - "on"
    - "in"
    - "to"
    - "for"
    - "of"
    - "with"
    - "by"
    - "from"
    - "up"
    - "out"
    - "off"
    - "over"
    - "under"
    - "about"
    - "into"
    - "through"
    - "during"
    - "before"
    - "after"
    - "above"
    - "below"
    - "between"
    - "among"
    - "this"
    - "that"
    - "these"
    - "those"
    - "all"
    - "any"
    - "some"
    - "many"
    - "few"
    - "each"
    - "every"
    - "both"
    - "either"
    - "neither"
    - "no"
    - "not"
    - "only"
    - "also"
    - "even"
    - "still"
    - "just"
    - "quite"
    - "very"
    - "so"
    - "too"
    - "more"
    - "most"
    - "less"
    - "least"
    - "much"
    - "little"
    - "long"
    - "short"
    - "high"
    - "low"
    - "big"
    - "small"
    - "good"
    - "bad"
    - "new"
    - "old"
    - "first"
    - "last"
    - "next"
    - "previous"
    - "same"
    - "different"
    - "other"
    - "another"
    - "such"
    - "own"
    - "right"
    - "left"
    - "whole"
    - "part"
    - "number"
    - "way"
    - "time"
    - "day"
    - "week"
    - "month"
    - "year"
    - "place"
    - "thing"
    - "person"
    - "work"
    - "life"
    - "hand"
    - "eye"
    - "back"
    - "head"
    - "side"
    - "end"
    - "start"
    - "begin"
    - "continue"
    - "stop"
    - "finish"
    - "complete"
    - "add"
    - "remove"
    - "delete"
    - "create"
    - "build"
    - "find"
    - "search"
    - "look"
    - "check"
    - "test"
    - "try"
    - "help"
    - "support"
    - "provide"
    - "allow"
    - "enable"
    - "disable"
    - "configure"
    - "setup"
    - "install"
    - "update"
    - "upgrade"
    - "download"
    - "upload"
    - "send"
    - "receive"
    - "read"
    - "write"
    - "open"
    - "close"
    - "start"
    - "restart"
    - "stop"
    - "pause"
    - "resume"
    - "cancel"
    - "submit"
    - "apply"
    - "process"
    - "handle"
    - "manage"
    - "control"
    - "monitor"
    - "track"
    - "log"
    - "record"
    - "store"
    - "load"
    - "access"
    - "connect"
    - "disconnect"
    - "login"
    - "logout"
    - "enter"
    - "exit"
    - "return"
    - "back"
    - "forward"
    - "next"
    - "previous"
    - "skip"
    - "wait"
    - "please"
    - "thank"
    - "thanks"
    - "welcome"
    - "hello"
    - "hi"
    - "goodbye"
    - "bye"
    - "yes"
    - "no"
    - "ok"
    - "okay"
    - "fine"
    - "great"
    - "good"
    - "better"
    - "best"
    - "well"
    - "nice"
