site:
  title: Peer-Review Platform Documentation
  url: https://gtrivedi88.github.io/peer-lens
  start_page: peer-lens::index.adoc

content:
  sources:
  - url: ../
    branches: HEAD
    edit_url: 'https://github.com/gtrivedi88/peer-lens/blob/main/{path}'
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./antora-lunr-ui

antora:
  extensions:
  - '@antora/lunr-extension'

runtime:
  log:
    failure_level: warn

asciidoc:
  attributes:
    source-highlighter: highlight.js
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
    page-mermaid: true
    experimental: ''
    icons: font
    sectanchors: ''
    sectlinks: ''
    stem: latexmath

output:
  dir: ./dist